#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#2, #recursive version timed out every when I tried to run it
import time


def fibUptoLimit(limit):
	a = 1
	b = 2
	sumOfEvenTerms = 2
	c = 0
	while True:
		
		c = a + b # next fibonacci number
		if c > limit:
			break
		a = b
		b = c
		# if even, add
		if c % 2 == 0:
			sumOfEvenTerms += c
	print sumOfEvenTerms

fibUptoLimit(10)
print '/'
fibUptoLimit(100)


